### ISSUE TITLE
Ran into a TypeError: iteration over a 0-d tensor

### ISSUE THREAD

**Issue by evazhang612** [nttcslab-nlp/doc_lm#3]
Error encountered after downloading codebase and running it: error traceback attached below. 

Command ran (as documented in README for PTB): 
`python main.py --data data/penn --dropouti 0.4 --dropoutl 0.6 --dropouth 0.225 --seed 28 --batch_size 12 --lr 20.0 --epoch 500 --nhid 960 --nhidlast 620 --emsize 280 --n_experts 15 --num4second 5 --var 0.001 --nonmono 60 --save PTB --single_gpu
`

> Traceback (most recent call last):
>   File "main.py", line 273, in <module>
>     train()
>   File "main.py", line 211, in train
>     hidden[s_id] = repackage_hidden(hidden[s_id])
>   File "/data/home/hony/doc_lm/utils.py", line 10, in repackage_hidden
>     return tuple(repackage_hidden(v) for v in h)
>   File "/data/home/hony/doc_lm/utils.py", line 10, in <genexpr>
>     return tuple(repackage_hidden(v) for v in h)
>   File "/data/home/hony/doc_lm/utils.py", line 10, in repackage_hidden
>     return tuple(repackage_hidden(v) for v in h)
>   File "/data/home/hony/doc_lm/utils.py", line 10, in <genexpr>
>     return tuple(repackage_hidden(v) for v in h)
>   File "/data/home/hony/doc_lm/utils.py", line 10, in repackage_hidden
>     return tuple(repackage_hidden(v) for v in h)
>   File "/data/home/hony/doc_lm/utils.py", line 10, in <genexpr>
>     return tuple(repackage_hidden(v) for v in h)
>   File "/data/home/hony/doc_lm/utils.py", line 10, in repackage_hidden
>     return tuple(repackage_hidden(v) for v in h)
>   File "/data/home/hony/doc_lm/utils.py", line 10, in <genexpr>
>     return tuple(repackage_hidden(v) for v in h)
>   File "/data/home/hony/doc_lm/utils.py", line 10, in repackage_hidden
>     return tuple(repackage_hidden(v) for v in h)
>   File "/data/home/hony/doc_lm/utils.py", line 10, in <genexpr>
>     return tuple(repackage_hidden(v) for v in h)
>   File "/data/home/hony/doc_lm/utils.py", line 10, in repackage_hidden
>     return tuple(repackage_hidden(v) for v in h)
>   File "/data/anaconda/envs/py35/lib/python3.5/site-packages/torch/tensor.py", line 422, in __iter__
>     raise TypeError('iteration over a 0-d tensor')
> TypeError: iteration over a 0-d tensor
>

**Comment by evazhang612** [comment]
Issue is due to compatibility with Pytorch version 1.0.0, seems to be resolved after downgrading to Pytorch in required version.
